@host = http://localhost:3001/api/v1/auth
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/sign-up
Content-Type: {{contentType}}

{
    "fullName": "Lê Xuân Hòa",
	"tel": "0364015071",
    "gender": false,
    "email": "dso.intern.xuanhoa@gmail.com",
    "roleId": 2
}

###
POST {{host}}/sign-in
Content-Type: {{contentType}}

{
    "email": "dso.intern.xuanhoa@gmail.com",
    "password": "dso.intern.xuanhoa@gmail.com"
}

###
GET {{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

###
PATCH {{host}}/reset-password
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "email": "training.dso.xuanhoa@gmail.com"
}