@host = http://localhost:3001/api/v1/auth
@contentType = application/json
@waiterAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblBheWxvYWQiOnsiYWNjb3VudElkIjo2LCJlbXBsb3llZUlkIjo4LCJyb2xlSWQiOjF9LCJleHAiOjE2OTc1NTQyNDUsImlhdCI6MTY5NzQ2Nzg0NX0.8Cc8rxwXGHxnoKOPnLwlJel2yPNy4O7WrzB4q46rT58

###
POST {{host}}/sign-up
Content-Type: {{contentType}}

{
    "fullName": "Le Xuan Hoa",
	"tel": "0364015071",
    "gender": false,
    "email": "dso.fresher.xuanhoa@gmail.com",
    "username": "dsoFresherXuanHoa",
    "password": "dsoFresherXuanHoa",
    "roleId": 2
}

###
POST {{host}}/sign-in
Content-Type: {{contentType}}

{
    "username": "dsoFresherXuanHoa",
    "password": "dsoFresherXuanHoa"
}

###
GET {{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}