@host = http://localhost:3001/api/v1/bills
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
PATCH {{host}}/finished/1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

###
PATCH {{host}}/compensated/?orderId=1&billId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}