@host = http://localhost:3001/api/v1/booking
@remote = http://139.144.118.48:3001/api/v1/booking
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}
@userAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@chiefAccessToken = {{$dotenv CHIEF_ACCESS_TOKEN}}

###
POST {{remote}}/
Content-Type: {{contentType}}
Authorization: Bearer {{userAccessToken}}

{
    "note": "Cho Vừa Vừa Hành Phi",
    "secretCode": 2226,
    "tableId": 29,
    "quantities": [3],
    "productsId": [1],
    "includeTableCost": true
}

### 
GET {{host}}/?orderId=24
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/employee
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/table/1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/table/preparing/3
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/table/rejected/2
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
POST {{host}}/accepted/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
POST {{remote}}/rejected/?orderId=14&reason="Không đủ nguyên liệu"
Content-Type: {{contentType}}
Authorization: Bearer {{chiefAccessToken}}

### 
PATCH {{host}}/finished/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

###
PATCH {{host}}/refund/1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "note": "Không Cho Hành Lá",
    "secretCode": 9416,
    "tableId": 1,
    "quantities": [2, 2],
    "productsId": [3, 2],
    "includeTableCost": true
}

### 
GET {{host}}/all
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}