@host = http://localhost:3001/api/v1/booking
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

{
    "note": "Không Cho Hành Lá",
    "secretCode": 7648,
    "tableId": 1,
    "quantities": [1, 3],
    "productsId": [3, 1],
    "refundable": false
}

### 
GET {{host}}/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/employee
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/table/1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
GET {{host}}/table/preparing/1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

### 
PATCH {{host}}/accepted/?orderId=4
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
PATCH {{host}}/rejected/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
PATCH {{host}}/finished/?orderId=4
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}