@host = http://localhost:3001/api/v1/booking
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "note": "Cho cay lên xíu nữa",
    "secretCode": 8594,
    "tableId": 2,
    "quantities": [1, 2],
    "productsId": [2, 1]
}

### 
PATCH {{host}}/accepted/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
PATCH {{host}}/rejected/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
PATCH {{host}}/finished/?orderId=2
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
GET {{host}}/?orderId=1
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

### 
PATCH {{host}}/compensated/?orderId=5
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}