@host = http://localhost:3001/api/v1/categories
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "name": "Điểm Tâm",
    "description": "Điểm Tâm, Thơm Ngon Bổ Dưỡng!"
}


###
GET {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}