@host = http://localhost:3001/api/v1/products
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
GET {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

###
GET {{host}}/category/3
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}


###
GET {{host}}/recommend/4
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

###
GET {{host}}/1
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}


###
DELETE {{host}}/20
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}