@host = http://localhost:3001/api/v1/products
@contentType = application/json
@managerAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblBheWxvYWQiOnsiYWNjb3VudElkIjo2LCJlbXBsb3llZUlkIjo4LCJyb2xlSWQiOjF9LCJleHAiOjE2OTc1NTQzNDEsImlhdCI6MTY5NzQ2Nzk0MX0.BBEdBsI7J8Tz5197oKUfTdRR6Xri5AZEiRRagfmoXHQ
@waiterAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblBheWxvYWQiOnsiYWNjb3VudElkIjozLCJlbXBsb3llZUlkIjo0LCJyb2xlSWQiOjJ9LCJleHAiOjE2OTc1NTc1NzYsImlhdCI6MTY5NzQ3MTE3Nn0.u15ilpRVodewGLUXf5x-YaN1HlLJ1yG1ahDQJoWZ3A0

// TODO: Get detail product
###
GET {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}

// TODO: Get detail product by categoryId
###
GET {{host}}/category/3
Content-Type: {{contentType}}
Authorization: Bearer {{waiterAccessToken}}