@host = http://localhost:3001/api/v1/roles
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}

{
    "name": "Chief"
}