@host = http://localhost:3001/api/v1/stats
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
GET {{host}}/employee/top/?startTime=1699478954&endTime=1699651754
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

###
GET {{host}}/goods/top/?startTime=1699478954&endTime=1699651754
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}