@host = http://localhost:3001/api/v1/tables
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "normalTable": false,
    "capacity": 15,
    "basePrice": 25000,
    "employeeId": 1,
    "areaId": 1
}

###
GET {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

###
GET {{host}}/status/true
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}


###
GET {{host}}/all
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}