@host = http://localhost:3001/api/v1/tables
@remote = https://food-delivery-api-f1u2.onrender.com/api/v1/tables
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{remote}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "normalTable": true,
    "capacity": 10,
    "basePrice": 0,
    "employeeId": 15,
    "areaId": 9
}

###
GET {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

###
GET {{host}}/status/true
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}


###
GET {{host}}/all
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}