@host = http://localhost:3001/api/v1/warehouses
@contentType = application/json
@formDataContentType = multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
@managerAccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlblBheWxvYWQiOnsiYWNjb3VudElkIjo2LCJlbXBsb3llZUlkIjo4LCJyb2xlSWQiOjF9LCJleHAiOjE2OTc1NTQzNDEsImlhdCI6MTY5NzQ2Nzk0MX0.BBEdBsI7J8Tz5197oKUfTdRR6Xri5AZEiRRagfmoXHQ

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "name": "Pessi",
    "description": "Pessi, Thơm Ngon Bổ Dưỡng",
    "price": 30000,
    "stockAmount": 200,
    "categoryId": 3,
    "minQuantity": 5,
    "discountPercent": 10
}

###
POST {{host}}/
Content-Type: {{formDataContentType}}
Authorization: Bearer {{managerAccessToken}}

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Gà Xào Xả Ớt
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Gà xào xả ớt, thêm ngon, bổ dưỡng
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

30000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stockAmount"

200
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="minQuantity"

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="discountPercent"

10
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="thumb;"

< "C:\Users\iset\Documents\Projects\GitHub\dsoFresherXuanHoa\go-food-delivery-api\asset\eacb2c360b44dc1a8555.jpg"
------WebKitFormBoundary7MA4YWxkTrZu0gW--