@host = http://localhost:3001/api/v1/warehouses
@contentType = application/json
@waiterAccessToken = {{$dotenv WAITER_ACCESS_TOKEN}}
@managerAccessToken = {{$dotenv MANAGER_ACCESS_TOKEN}}

###
POST {{host}}/
Content-Type: {{contentType}}
Authorization: Bearer {{managerAccessToken}}

{
    "name": "Pessi",
    "description": "Pessi, Thơm Ngon Bổ Dưỡng",
    "price": 5000,
    "stockAmount": 200,
    "categoryId": 3,
    "minQuantity": 5,
    "discountPercent": 10
}